export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SET_USER = "SET_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const RESET_AUTH_STATE = "RESET_AUTH_STATE";

export const DEVICE_ACTIONS = {
    FETCH_ALL_DEVICES: "FETCH_ALL_DEVICES",
    UPDATE_DEVICE: "UPDATE_DEVICE_STATUS"
}

export const DEVICE_REQUESTS_ACTIONS = {
    FETCH_ALL_REQUESTS: "FETCH_ALL_REQUESTS",
    UPDATE_REQUEST: "UPDATE_REQUEST"
}
