
export const AUTH_ACTIONS = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    SET_USER: "SET_USER",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT: "LOGOUT",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    RESET_AUTH_STATE: "RESET_AUTH_STATE",
}

export const DEVICE_ACTIONS = {
    FETCH_ALL_DEVICES: "FETCH_ALL_DEVICES",
    UPDATE_DEVICE: "UPDATE_DEVICE_STATUS"
}

export const DEVICE_REQUESTS_ACTIONS = {
    FETCH_ALL_REQUESTS: "FETCH_ALL_REQUESTS",
    UPDATE_REQUEST: "UPDATE_REQUEST"
}
